### PR TITLE
Do no escape urls in text nodes

### LINKED ISSUE #22: Characters inside plain text urls should not be escaped
Input:

```plaintext
https://text.com/some_page
```

Current output:

```plaintext
https://text.com/some\_page
```

Expected:

```plaintext
https://text.com/some_page
```

---

### Rational

All I can confirm is that the current output is broken when loaded in GitHub (it points to the url with backslash), not to the original url without it.

I can't confirm whether or not escaping is right or if this is a GitHub bug (by design?). And I can assume that GitHub will never change this, considering that amount of content it has already.

### PR DESCRIPTION
**Pull request by fredck**
Fixes domchristie/turndown#324 (previously #22 here).

### CODE REVIEW

**Comment by fredck** [comment]
Note that this change also upgrades dependencies because domchristie/turndown#324 happens in Turndown v5.

**Comment by martincizek** [comment]
As explained in [this comment at the corresponding issue](https://github.com/domchristie/turndown/issues/324#issuecomment-654226235), the escaping needs to be Markdown-context dependent in order to be correct.

domchristie/turndown#339 was filed to allow context-dependent processing and I'd also vote for a single-pass escaping mechanism (also referred to in domchristie/turndown#324) to allow treating similar cases systematically and without side effects.

**Comment by fredck** [comment]
Outdated

**Comment by martincizek** [comment]
Btw. this will be addressed when [gfm-escape](https://github.com/orchitech/gfm-escape) is integrated.

**Pull request closed without merging**
